// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZud2yCeSGzczLA1ydLLhDbgFCNUQeFE',
    appId: '1:622219047185:web:d619a773ee8d37bfad9cb0',
    messagingSenderId: '622219047185',
    projectId: 'pendura-donor',
    authDomain: 'pendura-donor.firebaseapp.com',
    storageBucket: 'pendura-donor.firebasestorage.app',
    measurementId: 'G-8ETEDVNFK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-2edhH_DvqpYW9PNAq2lqeCAOdcmzVQ',
    appId: '1:622219047185:android:852f68cc656f2d4aad9cb0',
    messagingSenderId: '622219047185',
    projectId: 'pendura-donor',
    storageBucket: 'pendura-donor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzO3eMPOwgG3f0Fr9zOKoYkbSSeALHv-U',
    appId: '1:622219047185:ios:428e6b775081c971ad9cb0',
    messagingSenderId: '622219047185',
    projectId: 'pendura-donor',
    storageBucket: 'pendura-donor.firebasestorage.app',
    iosBundleId: 'in.pendura.donor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzO3eMPOwgG3f0Fr9zOKoYkbSSeALHv-U',
    appId: '1:622219047185:ios:75957ebeeac4dae1ad9cb0',
    messagingSenderId: '622219047185',
    projectId: 'pendura-donor',
    storageBucket: 'pendura-donor.firebasestorage.app',
    iosBundleId: 'com.example.donor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEZud2yCeSGzczLA1ydLLhDbgFCNUQeFE',
    appId: '1:622219047185:web:639e6b82c2a8c8f6ad9cb0',
    messagingSenderId: '622219047185',
    projectId: 'pendura-donor',
    authDomain: 'pendura-donor.firebaseapp.com',
    storageBucket: 'pendura-donor.firebasestorage.app',
    measurementId: 'G-Y417EXC28E',
  );
}
